# Change these first
owner: tgstation-operations # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
skipDeleteIssues: true

sites:
  - name: Home Page
    url: https://tgstation13.org
    assignees:
      - MrStonedOne
  - name: Wiki
    url: https://tgstation13.org/wiki/Ping
    __dangerous__body_down_if_text_missing: "2623a561d632aqd1532frw"
    assignees:
      - MrStonedOne
  - name: Forum
    url: https://tgstation13.org/phpBB/viewtopic.php?p=302039
    __dangerous__body_down_if_text_missing: "ajA23jA32wj9fdafr32AcjACw3m"
    assignees:
      - MrStonedOne
  - name: VPN
    url: $SECRET_VPN_URL
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
    assignees:
      - MrStonedOne
  - name: TTS Webserver
    url: $SECRET_TTS_WEBSERVER_URL
    expectedStatusCodes:
      - 200
      - 201
      - 403
    assignees:
      - MrStonedOne
  - name: TTS API
    url: $SECRET_TTS_API_URL
    headers:
    - "Authorization: $SECRET_TTS_API_KEY"
    __dangerous__body_degraded_if_text_missing: "OK: "
    __dangerous__body_down_if_text_missing: ":"
    assignees:
      - MrStonedOne
  - name: TTS Generation
    url: $SECRET_TTS_TEST_GEN_URL
    headers:
    - "Content-Type: application/json"
    - "Accept: application/json"
    - "Authorization: $SECRET_TTS_API_KEY"
    body: '{ "text":"Help Maint" }'
    maxResponseTime: 500
    assignees:
      - MrStonedOne
  - name: Game Server Sybil
    url: sybil.game.tgstation13.org
    port: 1337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Basil
    url: Basil.game.tgstation13.org
    port: 2337
    check: "tcp-ping"
  - name: Game Server Terry
    url: Terry.game.tgstation13.org
    port: 3336
    check: "tcp-ping"
  - name: Game Server Manuel
    url: Manuel.game.tgstation13.org
    port: 1447
    check: "tcp-ping"
  - name: Game Server TGMC
    url: TGMC.game.tgstation13.org
    port: 5337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Campbell
    url: Campbell.game.tgstation13.org
    port: 6337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Events EU
    url: terry.game.tgstation13.org
    port: 4337
    check: "tcp-ping"
  - name: Game Server Events US
    url: basil.game.tgstation13.org
    port: 4447
    check: "tcp-ping"
  - name: DDoS-Relay EU-C-fra1-01
    url: http://165.227.138.121:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-fra1-02
    url: http://46.101.211.76:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-E-nyc1-01
    url: http://178.128.157.126:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-E-nyc1-02
    url: http://178.128.149.244:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-W-sfo3-01
    url: http://144.126.221.210:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-W-sfo3-02
    url: http://144.126.222.59:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-W-lon1-01
    url: http://165.22.122.245:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-W-lon1-02
    url: http://165.22.121.127:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay AU-syd1-01
    url: http://170.64.170.126:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay AU-syd1-02
    url: http://170.64.168.113:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  
  - name: DDoS-Relay lin-EU-C-fra-01
    url: http://139.162.181.177:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-EU-C-fra-02
    url: http://172.104.128.38:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-US-E-nj-01
    url: http://97.107.140.73:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-US-E-nj-02
    url: http://97.107.140.132:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-US-W-lax-01
    url: http://172.233.157.179:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-US-W-lax-02
    url: http://172.233.152.17:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-EU-W-lon2-01
    url: http://172.236.29.5:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay lin-AU-syd1-01
    url: http://194.195.251.189:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tgstation13.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tgstation-operations/status/master/assets/tglogo.svg
  faviconSvg: https://raw.githubusercontent.com/tgstation-operations/status/master/assets/tglogo.svg
  favicon: https://raw.githubusercontent.com/tgstation-operations/status/master/assets/tglogo.png
  theme: night
  name: "/tg/Station 13 Status"
  introTitle: "/tg/Station 13 Live Server Status"
  introMessage: This is a status page which uses **real-time** data from a [GitHub repository](https://github.com/tgstation-operations/status) generated by github runners pinging our services.
  navbar:
    - title: Status
      href: /
    - title: Status GitHub
      href: https://github.com/tgstation-operations/status
    - title: Main GitHub
      href: https://github.com/tgstation/tgstation
    - title: Discord
      href: https://discord.gg/tg13
    - title: Back To /tg/Station13
      href: https://tgstation13.org

workflowSchedule:
  graphs: "25 */4 * * *"
  responseTime: "20 */4 * * *"
  staticSite: "0 1 * * *"
  summary: "30 * * * *"
  updateTemplate: "0 0 1 * *"
  updates: "0 3 31 2 1"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "tgstation-server"
  commitAuthorEmail: "tgstation-server@tgstation13.org"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
