# Change these first
owner: tgstation-operations # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Home Page
    url: https://tgstation13.org
    assignees:
      - MrStonedOne
  - name: Wiki
    url: https://tgstation13.org/wiki/Ping
    __dangerous__body_down_if_text_missing: "2623a561d632aqd1532frw"
    assignees:
      - MrStonedOne
  - name: Forum
    url: https://tgstation13.org/phpBB/viewtopic.php?p=302039
    __dangerous__body_down_if_text_missing: "ajA23jA32wj9fdafr32AcjACw3m"
    assignees:
      - MrStonedOne
  - name: VPN
    url: $SECRET_VPN_URL
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
    assignees:
      - MrStonedOne
  - name: TTS Webserver
    url: $SECRET_TTS_WEBSERVER_URL
    expectedStatusCodes:
      - 200
      - 201
      - 403
    assignees:
      - MrStonedOne
  - name: TTS API
    url: $SECRET_TTS_API_URL
    headers:
    - "Authorization: $SECRET_TTS_API_KEY"
    __dangerous__body_degraded_if_text_missing: "OK: "
    __dangerous__body_down_if_text_missing: ":"
    assignees:
      - MrStonedOne
  - name: TTS Generation
    url: $SECRET_TTS_TEST_GEN_URL
    headers:
    - "Content-Type: application/json"
    - "Accept: application/json"
    - "Authorization: $SECRET_TTS_API_KEY"
    body: '{ "text":"Help Maint" }'
    maxResponseTime: 500
    assignees:
      - MrStonedOne
  - name: Game Server Sybil
    url: sybil.game.tgstation13.org
    port: 1337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Basil
    url: Basil.game.tgstation13.org
    port: 2337
    check: "tcp-ping"
  - name: Game Server Terry
    url: Terry.game.tgstation13.org
    port: 3336
    check: "tcp-ping"
  - name: Game Server Manuel
    url: Manuel.game.tgstation13.org
    port: 1447
    check: "tcp-ping"
  - name: Game Server TGMC
    url: TGMC.game.tgstation13.org
    port: 5337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Campbell
    url: Campbell.game.tgstation13.org
    port: 6337
    check: "tcp-ping"
    assignees:
      - MrStonedOne
  - name: Game Server Events EU
    url: terry.game.tgstation13.org
    port: 4337
    check: "tcp-ping"
  - name: Game Server Events US
    url: basil.game.tgstation13.org
    port: 4447
    check: "tcp-ping"
  - name: DDoS-Relay EU-C-fsn1-1
    url: http://162.55.41.97:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-fsn1-2
    url: http://188.245.51.2:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-fsn1-3
    url: http://188.245.48.186:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-fsn1-4
    url: http://142.132.232.192:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-nbg1-2
    url: http://128.140.75.62:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-nbg1-4
    url: http://128.140.77.59:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay EU-C-nbg1-6
    url: http://188.245.105.186:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-E-ash-1
    url: http://5.161.250.73:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-E-ash-2
    url: http://5.161.186.237:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-E-ash-4
    url: http://5.161.201.13:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-W-hil-1
    url: http://5.78.91.168:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-W-hil-2
    url: http://5.78.111.66:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"
  - name: DDoS-Relay US-W-hil-3
    url: http://5.78.64.252:42069/;csv
    __dangerous__body_degraded_if_text_missing: ",UP,"
    __dangerous__body_down_if_text_missing: "OPEN"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tgstation13.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tgstation-operations/status/master/assets/tglogo.svg
  faviconSvg: https://raw.githubusercontent.com/tgstation-operations/status/master/assets/tglogo.svg
  theme: night
  name: "/tg/Station 13 Status"
  introTitle: "/tg/Station 13 Live Server Status"
  introMessage: This is a status page which uses **real-time** data from a [GitHub repository](https://github.com/tgstation-operations/status) generated by github runners pinging our services.
  navbar:
    - title: Status
      href: /
    - title: Status GitHub
      href: https://github.com/tgstation-operations/status
    - title: Main GitHub
      href: https://github.com/tgstation/tgstation
    - title: Discord
      href: https://discord.gg/tg13
    - title: Back To /tg/Station13
      href: https://tgstation13.org

workflowSchedule:
  graphs: "25 */4 * * *"
  responseTime: "20 */4 * * *"
  staticSite: "0 1 * * *"
  summary: "30 * * * *"
  updateTemplate: "0 0 1 * *"
  updates: "0 3 31 2 1"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "tgstation-server"
  commitAuthorEmail: "tgstation-server@tgstation13.org"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
